json.extract! @spot, 
        :id,
        :name, 
        :address1, 
        :address2, 
        :city, 
        :state, 
        :zipcode, 
        :longitude, 
        :latitude, 
        :price, 
        :acres, 
        :capacity, 
        :about, 
        :lodgings, 
        :rvs, 
        :tents, 
        :high_demand, 
        :owner_id

        json.photo_urls @spot.photos.map{ |file| file.url }